package com.utdallas.movierental.frequentRenterPoints.rental;

import com.utdallas.movierental.frequentRenterPoints.FrequentRenterPointsStrategy;
import com.utdallas.movierental.frequentRenterPoints.FrequentRenterPointsStrategyNewReleaseType;

public class FrequentRenterPointsRentalStrategyNewReleaseType extends FrequentRenterPointsStrategyNewReleaseType {

}
