package com.utdallas.movierental.frequentRenterPoints.rental;

import com.utdallas.movierental.frequentRenterPoints.FrequentRenterPointsStrategy;
import com.utdallas.movierental.frequentRenterPoints.FrequentRenterPointsStrategyChildrensType;

public class FrequentRenterPointsRentalStrategyChildrensType extends FrequentRenterPointsStrategyChildrensType {

}
