package com.utdallas.movierental.frequentRenterPoints.rental;

import com.utdallas.movierental.frequentRenterPoints.FrequentRenterPointsStrategy;
import com.utdallas.movierental.frequentRenterPoints.FrequentRenterPointsStrategyRegularType;

public class FrequentRenterPointsRentalStrategyRegularType extends FrequentRenterPointsStrategyRegularType {

}
